export const products = [
  {
    id: "buds-pro",
    name: "Mizazy Wireless Buds 104",
    title:
      "Mizazy Wireless Buds 104 TWS Earbuds with 35H Backup, Bluetooth 5.0, Quad Mic, Environmental Noise Cancellation & HD Sound",
    slug: "mizazy-wireless-buds-104",
    metaTitle: "Mizazy Wireless Buds 104 | 35H Backup | Bluetooth 5.0 | ₹1,499",
    metaDescription:
      "Buy Mizazy Wireless Buds 104 TWS Earbuds with 35H backup, Bluetooth 5.0, Quad Mic, Environmental Noise Cancellation, Google Fast Pairing and HD Sound at ₹1,499.",
    tagline: "35H Backup | Bluetooth 5.0 | Quad Mic | ENC | HD Sound",
    tags: ["35H Backup", "Bluetooth 5.0", "Quad Mic", "HD Sound"],
    description:
      "Experience wireless audio with the Mizazy Wireless Buds 104. Featuring Bluetooth 5.0, up to 35 hours of total backup with the charging case, Environmental Noise Cancellation, Google Fast Pairing, Quad Mic, In-Ear Detection, HD Sound and a lightweight design, these TWS earbuds are designed for music, calls and everyday entertainment.",
    price: 1499,
    mrp: 1999,
    rating: 4.8,
    reviews: 2847,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790761956/Mizazy_Earbuds_104_Black_Front.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790614191/Mizazy_Earbuds_White.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790761956/Mizazy_Earbuds_104_Black_Front.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790761956/Mizazy_Earbuds_104_Black_Side1.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790761957/Mizazy_Earbuds_104_Black_Side.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761956/Mizazy_Earbuds_104_Black_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761956/Mizazy_Earbuds_104_Black_Side1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761957/Mizazy_Earbuds_104_Black_Side.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761961/Mizazy_Earbuds_104_Blue_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761962/Mizazy_Earbuds_104_Blue_Front1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761964/Mizazy_Earbuds_104_Blue_Side.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761958/Mizazy_Earbuds_104_White_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761963/Mizazy_Earbuds_104_White_Side.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790761963/Mizazy_Earbuds_104_White_Front_1.png",
      ],
    ],
    badge: "BEST SELLER",
    colors: ["#111111", "#1E4FA8", "#F5F5F5"],
    colorNames: ["Black", "Blue", "White"],
    category: "Audio / TWS Earbuds",
    features: [
      "Up to 35 Hours Backup with Charging Case",
      "Bluetooth 5.0",
      "Environmental Noise Cancellation",
      "Google Fast Pairing",
      "Quad Mic",
      "In-Ear Detection",
      "HD Sound",
      "Hands-Free Calling",
      "Built-in Microphone",
      "One-Key Reset",
      "Lightweight Design",
      "Wireless Connectivity",
      "Available in Black, Blue & White",
    ],
    keyFeatures: [
      {
        title: "35-Hour Backup",
        text: "The product packaging states approximately 35 hours of working time with the charging case.",
      },
      {
        title: "Environmental Noise Cancellation",
        text: "The packaging lists Environmental Noise Cancellation as a product feature designed to improve the calling/audio experience in suitable environments.",
      },
      {
        title: "Google Fast Pairing",
        text: "Supports Google Fast Pairing as mentioned on the product packaging for convenient device pairing.",
      },
      { title: "Quad Mic", text: "The product features a Quad Mic system as stated on the packaging." },
      {
        title: "In-Ear Detection",
        text: "The earbuds feature In-Ear Detection for a more convenient listening experience.",
      },
      { title: "HD Sound", text: "The packaging highlights HD Sound for music and entertainment." },
      {
        title: "Hands-Free Calling",
        text: "The product supports hands-free calling through its built-in microphones.",
      },
      { title: "One-Key Reset", text: "A One-Key Reset feature is listed on the packaging." },
      { title: "Lightweight Design", text: "The packaging highlights the product as lightweight." },
      {
        title: "Wireless Connectivity",
        text: "The earbuds use Bluetooth wireless connectivity for compatible devices.",
      },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "104",
      Model: "104",
      "Product Type": "True Wireless Stereo (TWS) Earbuds",
      Subcategory: "Wireless Earbuds",
      "Bluetooth Version": "5.0",
      "Radio Frequency (Bluetooth)": "2.4GHz – 2.435GHz",
      "Total Working Time": "About 35 Hours with Charging Case",
      "Earphone Charging Time": "About 1–2 Hours",
      "Charging Case Charging Time": "About 2–3 Hours",
      "Charging Case Battery Capacity": "300mAh",
      "TWS Buds Battery Capacity": "45mAh",
      Sound: "HD Sound",
      Microphones: "Quad Mic",
      "Noise Feature": "Environmental Noise Cancellation",
      Pairing: "Google Fast Pairing",
      "In-Ear Detection": "Yes",
      Reset: "One-Key Reset",
      Connectivity: "Wireless / Bluetooth",
      Design: "Lightweight",
      Colours: "Black, Blue, White",
      "Country of Origin": "India",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    inBox: ["1 × Mizazy Wireless Buds 104 TWS Earbuds", "1 × Charging Case"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy Wireless Buds 104 TWS Earbuds." },
      { q: "What is the Bluetooth version?", a: "The earbuds support Bluetooth 5.0." },
      {
        q: "How much backup does the product provide?",
        a: "The packaging states approximately 35 hours of working time with the charging case.",
      },
      { q: "What is the battery capacity of the charging case?", a: "The charging case has a 300mAh battery capacity." },
      {
        q: "What is the battery capacity of the earbuds?",
        a: "The TWS buds have a 45mAh battery capacity as specified on the packaging.",
      },
      {
        q: "How long does it take to charge the earbuds?",
        a: "The packaging specifies approximately 1–2 hours for earphone charging.",
      },
      { q: "How long does the charging case take to charge?", a: "The packaging specifies approximately 2–3 hours." },
      { q: "Does it have a microphone?", a: "Yes. The product features a Quad Mic system." },
      {
        q: "Does it support hands-free calling?",
        a: "Yes. It is designed for hands-free calling and includes built-in microphones.",
      },
      {
        q: "Does it have Environmental Noise Cancellation?",
        a: "Yes. Environmental Noise Cancellation is listed as a product feature on the packaging.",
      },
      { q: "Does it support Google Fast Pairing?", a: "Yes. Google Fast Pairing is listed on the packaging." },
      { q: "Does it have In-Ear Detection?", a: "Yes. In-Ear Detection is listed as one of the product features." },
      { q: "Does it provide HD Sound?", a: "Yes. HD Sound is listed on the packaging." },
      { q: "Does it have a reset function?", a: "Yes. The product includes a One-Key Reset feature." },
      { q: "What colours are available?", a: "Black, Blue and White." },
      { q: "Is it wireless?", a: "Yes. The earbuds use Bluetooth wireless connectivity." },
      { q: "Is the charging case included?", a: "Yes. The earbuds are supplied with a charging case." },
      {
        q: "Is a charging cable included?",
        a: "A charging cable is not listed in the box contents. The box includes the earbuds and the charging case.",
      },
    ],
    emi: undefined,
    stock: 48,
  },
  {
    id: "watch-x1",
    name: "Mizazy 120W Fast USB Data Cable",
    title:
      "Mizazy 120W Fast USB Data Cable USB-A to Type-C, Fast Charging, High-Speed Data Sync, Metallic Connectors, 1 Meter Durable Cable",
    slug: "mizazy-120w-fast-usb-data-cable",
    metaTitle: "Mizazy 120W Fast USB Data Cable | USB-A to Type-C | ₹349",
    metaDescription:
      "Buy Mizazy 120W Fast USB Data Cable with USB-A to Type-C connectivity, fast charging support, high-speed data sync, metallic connectors, durable PVC jacket and 1M length at ₹349.",
    ogTitle: "Mizazy 120W Fast USB Data Cable | USB-A to Type-C",
    ogDescription:
      "Mizazy 120W Fast USB Data Cable with USB-A to Type-C connectivity, fast charging support, high-speed data sync, metallic connectors and 1M durable PVC jacket. Get it at ₹349.",
    imageAlt: "Mizazy 120W Fast USB-A to Type-C Data Cable",
    imageTitle: "Mizazy 120W Fast USB Data Cable",
    seoKeywords: [
      "Mizazy data cable",
      "Mizazy Type-C cable",
      "Mizazy USB cable",
      "120W data cable",
      "120W fast charging cable",
      "USB-A to Type-C cable",
      "Type-C fast charging cable",
      "fast charging data cable",
      "high-speed data sync cable",
      "1 meter Type-C cable",
      "metallic connector cable",
      "PVC jacket Type-C cable",
      "Mizazy USB-A to Type-C",
      "Mizazy",
      "Data Cable",
      "Type-C Cable",
      "USB-A to Type-C",
      "120W Cable",
      "Fast Charging Cable",
      "High-Speed Data Sync",
      "Metallic Connector",
      "PVC Cable",
      "1 Meter Cable",
      "Mobile Accessories",
    ],
    tagline: "120W Max Output | USB-A to Type-C | High-Speed Data Sync | 1M",
    tags: ["120W Max Output", "Fast Charging", "High-Speed Data Sync", "1M Length", "Metallic Connectors", "Tangle-Free"],
    description:
      "Power your compatible devices with the Mizazy 120W Fast USB Data Cable. Featuring USB-A to Type-C connectivity, support for up to 120W maximum output, high-speed data synchronization, metallic connectors and a durable PVC jacket, this 1-meter cable is designed for everyday charging and data transfer with compatible smartphones, tablets, laptops and other Type-C devices.",
    price: 349,
    mrp: 549,
    rating: 4.7,
    reviews: 1523,
    image:
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780281/Mizazy_120W_Fast_USB_Data_Cable2.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790709469/Mizazy_Black_Cable.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780281/Mizazy_120W_Fast_USB_Data_Cable2.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780285/Mizazy_120W_Fast_USB_Data_Cable.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780281/Mizazy_120W_Fast_USB_Data_Cable1.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780281/Mizazy_120W_Fast_USB_Data_Cable2.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780285/Mizazy_120W_Fast_USB_Data_Cable.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780281/Mizazy_120W_Fast_USB_Data_Cable1.png",
      ],
    ],
    badge: "NEW",
    colors: ["#111111"],
    colorNames: ["Black"],
    category: "Mobile Accessories / Cables",
    isNew: true,
    features: [
      "120W Max Output",
      "Fast Charging Support",
      "USB-A to Type-C",
      "High-Speed Data Sync",
      "Metallic Connectors",
      "Durable PVC Jacket",
      "Tangle-Free Design",
      "Durable Cable Build",
      "Safe Charging",
      "Over-Current Protection",
      "Over-Voltage Protection",
      "1 Meter Length",
      "Compatible with Smartphones, Tablets, Laptops & More",
    ],
    keyFeatures: [
      {
        title: "120W Max Output",
        text: "The product packaging highlights a maximum output of up to 120W. Actual charging speed depends on the connected charger, device and supported charging technology.",
      },
      {
        title: "Fast Charging Support",
        text: "Designed to support fast charging for compatible smartphones, tablets, laptops and other compatible devices.",
      },
      {
        title: "USB-A to Type-C Connectivity",
        text: "The cable features a USB-A connector on one end and a Type-C connector on the other.",
      },
      { title: "High-Speed Data Sync", text: "The cable supports high-speed data synchronization with compatible devices." },
      {
        title: "Metallic Connectors",
        text: "The packaging highlights metallic connectors for a premium look and durable construction.",
      },
      { title: "Durable PVC Jacket", text: "The cable features a PVC jacket designed for regular everyday use." },
      {
        title: "Tangle-Free Design",
        text: "The packaging highlights a tangle-free design for convenient handling and storage.",
      },
      {
        title: "Safe Charging",
        text: "The product packaging highlights safe charging with over-current and over-voltage protection.",
      },
      {
        title: "1-Meter Length",
        text: "The cable has a 1-meter length, making it suitable for everyday charging and data synchronization.",
      },
      {
        title: "Wide Compatibility",
        text: "The packaging states compatibility with smartphones, tablets, laptops and more, subject to compatible USB-A and Type-C ports.",
      },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "Data Cable",
      Model: "Data Cable",
      "Product Type": "Fast USB Data Cable",
      Subcategory: "USB-A to Type-C Cable",
      "Connector Type": "USB-A to Type-C",
      "Maximum Output": "120W Max",
      Function: "Charging + Data Sync",
      "Cable Material": "PVC Jacket",
      "Connector Material": "Metallic Connectors",
      "Cable Length": "1 Meter",
      Design: "Tangle-Free & Durable",
      Protection: "Over-Current Protection, Over-Voltage Protection",
      Compatibility: "Smartphones, Tablets, Laptops & More",
      Colour: "Black",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    infoSections: [
      {
        title: "Charging Information",
        items: [
          { label: "Maximum Output", value: "120W Max" },
          { label: "Charging", value: "Fast Charging Support" },
          { label: "Protection", value: "Over-Current Protection, Over-Voltage Protection" },
        ],
        notes: [
          "The packaging states 120W maximum output.",
          "Actual charging speed depends on the connected charger, device, charging protocol and hardware limitations.",
        ],
      },
      {
        title: "Data Transfer Information",
        items: [{ label: "Function", value: "High-Speed Data Sync" }],
        notes: ["The cable is designed for charging and data synchronization with compatible devices."],
      },
    ],
    inBox: ["1 × Mizazy 120W Fast USB Data Cable USB-A to Type-C"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy 120W Fast USB Data Cable." },
      { q: "What type of cable is this?", a: "It is a USB-A to Type-C fast charging data cable." },
      { q: "What is the maximum output of the cable?", a: "The packaging highlights a maximum output of up to 120W." },
      {
        q: "Does the cable support fast charging?",
        a: "Yes. The product is designed for fast charging with compatible devices and chargers.",
      },
      {
        q: "Does the cable support data transfer?",
        a: "Yes. It supports high-speed data synchronization with compatible devices.",
      },
      {
        q: "What type of connectors does it have?",
        a: "It has a USB-A connector on one end and a Type-C connector on the other.",
      },
      { q: "What is the cable length?", a: "The cable is 1 meter long." },
      { q: "What material is used for the cable?", a: "The packaging specifies a PVC jacket and metallic connectors." },
      { q: "Is the cable tangle-free?", a: "Yes. A tangle-free design is highlighted on the product packaging." },
      {
        q: "Does the cable have charging protection?",
        a: "Yes. The packaging highlights over-current and over-voltage protection.",
      },
      {
        q: "Which devices are compatible with this cable?",
        a: "The packaging states compatibility with smartphones, tablets, laptops and more, provided the devices have compatible USB-A/Type-C connections.",
      },
      {
        q: "Does every device support 120W charging with this cable?",
        a: "No. Actual charging speed depends on the device, charger and supported charging technology.",
      },
      {
        q: "Is the charger included?",
        a: "No. The product listing is for the data cable only. A compatible charger/power adapter is required separately.",
      },
      { q: "What colour is available?", a: "Black." },
      { q: "What is the MRP?", a: "The MRP is ₹549." },
      { q: "What is the offer price?", a: "The offer price is ₹349." },
      { q: "How much can I save?", a: "You save ₹200 compared with the listed MRP." },
      { q: "What is included in the box?", a: "1 × Mizazy 120W Fast USB Data Cable USB-A to Type-C." },
    ],
    emi: undefined,
    stock: 32,
  },
  {
    id: "soundmax-pro",
    name: "Mizazy Buds X Prime",
    title:
      "Mizazy Buds X Prime True Wireless Earbuds with Bluetooth 5.0, 40H Backup, HD Sound & Built-in Mic",
    slug: "mizazy-buds-x-prime-tws-earbuds",
    metaTitle: "Mizazy Buds X Prime TWS Earbuds | Bluetooth 5.0 | 40H Backup",
    metaDescription:
      "Buy Mizazy Buds X Prime TWS Earbuds with Bluetooth 5.0, HD sound, built-in mic and up to 40 hours backup with charging case. Available in Black and Green at ₹1,199.",
    imageAlt: "Mizazy Buds X Prime True Wireless Earbuds",
    tagline: "Bluetooth 5.0 | 40H Backup | HD Sound | Built-in Mic",
    tags: [
      "🎧 True Wireless Earbuds",
      "🔋 Up to 40H Backup",
      "📶 Bluetooth 5.0",
      "🎙️ Built-in Mic",
      "🔊 HD Sound",
      "📞 Hands-Free Calling",
      "⚡ Long Music & Talk Time",
      "🪶 Lightweight Design",
    ],
    description:
      "Enjoy wireless freedom and immersive audio with the Mizazy Buds X Prime. Designed with Bluetooth 5.0, HD sound, built-in microphones and up to 40 hours of total backup with the charging case, these lightweight TWS earbuds are suitable for music, calls and everyday entertainment.",
    price: 1199,
    mrp: 1599,
    rating: 4.9,
    reviews: 986,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790597307/Mizazy_Black_Earbuds_video.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front-open.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front-closed.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front-open.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763058/Mizazy_Earbuds_Black_40H_Front-closed.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763060/Mizazy_Earbuds_Green_40H_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763061/Mizazy_Earbuds_Green_40H_Side-closed.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790763065/Mizazy_Earbuds_Green_40H_Side-open.png",
      ],
    ],
    badge: undefined,
    colors: ["#111111", "#1F7A4D"],
    colorNames: ["Black", "Green"],
    category: "Audio / TWS Earbuds",
    features: [
      "Up to 40 Hours Backup with Charging Case",
      "Bluetooth 5.0",
      "HD Sound",
      "Built-in Microphone",
      "Hands-Free Calling",
      "Ultra Long Talk / Music",
      "Lightweight Design",
      "Wireless Connectivity",
      "Environmental Sound Control",
      "Compact Charging Case",
      "Available in Black & Green",
    ],
    keyFeatures: [
      {
        title: "40 Hours Backup",
        text: "The packaging states approximately 40 hours of working time with the charging case.",
      },
      { title: "Bluetooth 5.0", text: "Provides wireless connectivity with compatible Bluetooth-enabled devices." },
      { title: "HD Sound", text: "Designed to provide an HD sound experience for music and entertainment." },
      {
        title: "Built-in Microphone",
        text: "Built-in microphone support for hands-free calling and voice communication.",
      },
      {
        title: "Hands-Free Calling",
        text: "Designed for convenient wireless calling without directly holding the smartphone.",
      },
      { title: "Ultra Long Talk / Music", text: "Designed for extended music playback and calling." },
      {
        title: "Lightweight Design",
        text: "The packaging highlights the earbuds as lightweight for convenient everyday use.",
      },
      { title: "Environment Sound Control", text: "The packaging lists Environment Sound Control as a product feature." },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "Buds X Prime",
      "Product Type": "True Wireless Stereo (TWS) Earbuds",
      Model: "Buds X Prime",
      "Bluetooth Version": "5.0",
      "Total Working Time": "About 40 Hours with Charging Case",
      "Earphone Charging Time": "About 1–2 Hours",
      "Charging Case Charging Time": "About 2–3 Hours",
      "Charging Case Battery Capacity": "300mAh",
      "TWS Buds Battery Capacity": "45mAh",
      Sound: "HD Sound",
      Microphone: "Built-in Mic",
      Calling: "Hands-Free Calling",
      Connectivity: "Wireless / Bluetooth",
      Design: "Lightweight",
      Colours: "Black, Green",
      "Country of Origin": "India",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    inBox: ["1 × Mizazy Buds X Prime TWS Earbuds set", "Charging Case"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy Buds X Prime True Wireless Earbuds." },
      { q: "What Bluetooth version does it support?", a: "Bluetooth 5.0." },
      {
        q: "How much backup does the product provide?",
        a: "The packaging states approximately 40 hours of working time with the charging case.",
      },
      {
        q: "What is the battery capacity of the charging case?",
        a: "The charging case has a 300mAh battery capacity as stated on the packaging.",
      },
      {
        q: "What is the battery capacity of each TWS bud?",
        a: "The packaging specifies a 45mAh battery capacity for the TWS buds.",
      },
      {
        q: "How long does it take to charge the earbuds?",
        a: "The packaging specifies approximately 1–2 hours for earphone charging.",
      },
      { q: "How long does the charging case take to charge?", a: "The packaging specifies approximately 2–3 hours." },
      { q: "Does it have a built-in microphone?", a: "Yes. It has a built-in microphone." },
      { q: "Can I use it for phone calls?", a: "Yes. The product supports hands-free calling." },
      { q: "Does it support HD sound?", a: "Yes. HD Sound is listed on the product packaging." },
      { q: "Is it lightweight?", a: "Yes. Lightweight design is listed as one of the product features." },
      { q: "What colours are available?", a: "Black and Green." },
      { q: "Is it wireless?", a: "Yes. It is a wireless Bluetooth TWS earbud product." },
      {
        q: "Does it come with a charging case?",
        a: "Yes. The product is supplied with a charging case, which contributes to the stated total backup time.",
      },
    ],
    emi: undefined,
    stock: 27,
  },
  {
    id: "neckpro",
    name: "Mizazy 20W USB-C Power Adapter for iPhone",
    title:
      "Mizazy 20W USB-C Fast Charger Power Adapter for iPhone | iPhone Compatible PD Charger | Compact & Portable Wall Charger | Fast Charging | Safe & Reliable Charging",
    slug: "mizazy-20w-usb-c-fast-charger-for-iphone",
    metaTitle: "Mizazy 20W USB-C Fast Charger for iPhone | Power Adapter | ₹899",
    metaDescription:
      "Buy Mizazy 20W USB-C Fast Charger for iPhone at ₹899. iPhone compatible, compact and portable USB-C PD power adapter with fast charging and multiple safety protection features for iPhone, iPad and other compatible devices.",
    ogTitle: "Mizazy 20W USB-C Fast Charger for iPhone | Fast Charging Power Adapter",
    ogDescription:
      "Mizazy 20W USB-C Fast Charger for iPhone with compact design, iPhone compatible fast charging support and multiple safety protection features. Get it at an offer price of ₹899.",
    imageAlt: "Mizazy 20W USB-C Fast Charger Power Adapter for iPhone",
    imageTitle: "Mizazy 20W USB-C Fast Charger for iPhone",
    seoKeywords: [
      "Mizazy 20W charger",
      "Mizazy USB-C charger",
      "20W fast charger",
      "USB-C fast charger",
      "USB-C power adapter",
      "Type-C charger",
      "20W USB-C adapter",
      "fast charging adapter",
      "mobile fast charger",
      "USB-C wall charger",
      "Mizazy",
      "USB-C Charger",
      "20W Charger",
      "Fast Charger",
      "Power Adapter",
      "Mobile Charger",
      "USB-C Adapter",
      "Chargers & Power Adapters",
      "iPhone charger",
      "20W iPhone charger",
      "iPhone fast charger",
      "iPhone compatible charger",
      "USB-C charger for iPhone",
      "20W PD charger for iPhone",
      "iPhone power adapter",
      "iPad charger",
    ],
    tagline: "20W Fast Charging | USB-C Output | iPhone Compatible | Compact | Safe Charging",
    tags: ["20W Fast Charging", "USB-C", "iPhone Compatible", "Compact Design", "Safe Charging"],
    description:
      "Charge your compatible devices quickly and conveniently with the Mizazy 20W USB-C Power Adapter. Designed with a USB-C output, compact portable design and multiple safety protection features, this wall charger is suitable for compatible smartphones, tablets and other USB-C enabled devices. It is iPhone compatible and supports USB-C PD fast charging on supported iPhone and iPad models when used with a compatible USB-C to Lightning or USB-C to USB-C cable.",
    price: 899,
    mrp: 1599,
    rating: 4.4,
    reviews: 5623,
    image:
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790776488/Mizazy_20W_USB-C_Power_Adapter_Front.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790682638/Iphone_Adapter.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790776488/Mizazy_20W_USB-C_Power_Adapter_Front.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790776486/Mizazy_20W_USB-C_Power_Adapter_Stand.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790776485/Mizazy_20W_USB-C_Power_Adapter_Backside.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790776488/Mizazy_20W_USB-C_Power_Adapter_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790776486/Mizazy_20W_USB-C_Power_Adapter_Stand.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790776485/Mizazy_20W_USB-C_Power_Adapter_Backside.png",
      ],
    ],
    badge: "LIMITED",
    colors: ["#F5F5F5"],
    colorNames: ["White"],
    category: "Mobile Accessories / Chargers",
    features: [
      "Up to 20W Fast Charging",
      "USB-C Output",
      "Compact & Portable Design",
      "Fast & Efficient Charging",
      "Safe & Reliable Charging",
      "Over-Voltage Protection",
      "Over-Current Protection",
      "Short-Circuit Protection",
      "Over-Temperature Protection",
      "Compatible with USB-C Devices",
      "iPhone Compatible (USB-C PD Fast Charging)",
      "Suitable for Home, Office & Travel",
      "Available in White",
    ],
    keyFeatures: [
      { title: "20W Fast Charging", text: "The charger supports up to 20W maximum output for compatible devices." },
      {
        title: "USB-C Output",
        text: "Features a USB-C charging port for convenient charging with compatible USB-C cables.",
      },
      {
        title: "Compact & Portable",
        text: "Its compact design makes it convenient for use at home, office or while travelling.",
      },
      {
        title: "Multiple Safety Protections",
        text: "Designed with protection against over-voltage, over-current, short circuits and overheating.",
      },
      {
        title: "Fast & Efficient Charging",
        text: "Designed to provide fast and efficient charging to compatible USB-C devices.",
      },
      {
        title: "Wide Compatibility",
        text: "Suitable for compatible smartphones, tablets and other USB-C enabled devices.",
      },
      {
        title: "iPhone Compatible",
        text: "Supports USB-C PD fast charging on supported iPhone and iPad models with a compatible USB-C to Lightning or USB-C to USB-C cable.",
      },
      { title: "Reliable Everyday Charging", text: "Designed for safe and stable everyday charging performance." },
      {
        title: "Plug & Play",
        text: "Simply connect a compatible USB-C cable and compatible device to begin charging.",
      },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "20W USB-C Power Adapter",
      Model: "20W USB-C Power Adapter",
      "Product Type": "USB-C Power Adapter / Wall Charger",
      Subcategory: "USB-C Power Adapter",
      "Maximum Output": "20W",
      "Output Port": "USB-C",
      "Charging Technology": "Fast Charging",
      "Output Interface": "USB-C",
      Input: "AC Power",
      "Safety Protection":
        "Over-Voltage Protection, Over-Current Protection, Short-Circuit Protection, Over-Temperature Protection",
      Design: "Compact & Portable",
      Compatibility: "Compatible USB-C Enabled Devices, iPhone & iPad (supported models)",
      Usage: "Home / Office / Travel",
      Colour: "White",
      "Country of Origin": "India",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    inBox: ["1 × Mizazy 20W USB-C Power Adapter", "1 × Product Packaging"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy 20W USB-C Power Adapter." },
      {
        q: "What is the maximum output of this charger?",
        a: "The charger supports up to 20W maximum output for compatible devices.",
      },
      { q: "Does the charger have a USB-C port?", a: "Yes. It features a USB-C output port." },
      {
        q: "Does it support fast charging?",
        a: "Yes. It is designed to support fast charging up to 20W on compatible devices.",
      },
      {
        q: "Which devices can be charged with this adapter?",
        a: "It can be used with compatible USB-C enabled smartphones, tablets and other USB-C devices.",
      },
      {
        q: "Is this charger compatible with iPhone?",
        a: "Yes. It is iPhone compatible and supports USB-C PD fast charging on supported iPhone models when used with a compatible USB-C to Lightning or USB-C to USB-C cable (sold separately).",
      },
      {
        q: "Is the charging cable included?",
        a: "No. The box contains the power adapter with its product packaging, so a compatible USB-C charging cable is required separately.",
      },
      {
        q: "Does it have safety protection?",
        a: "Yes. The charger is designed with over-voltage, over-current, short-circuit and over-temperature protection.",
      },
      { q: "Is the charger portable?", a: "Yes. Its compact design makes it suitable for home, office and travel use." },
      { q: "What colour is available?", a: "White." },
      { q: "What is the MRP?", a: "The MRP is ₹1,599." },
      { q: "What is the offer price?", a: "The offer price is ₹899." },
      { q: "How much can I save?", a: "You save ₹700 compared with the listed MRP." },
      { q: "What is included in the box?", a: "1 Mizazy 20W USB-C Power Adapter with product packaging." },
      {
        q: "Does every device charge at 20W?",
        a: "No. Actual charging speed depends on the connected device, cable and supported charging protocol.",
      },
    ],
    emi: undefined,
    stock: 73,
  },
  {
    id: "gan-65w",
    name: "Mizazy 135W Super Fast Charger",
    title:
      "Mizazy 135W Super Fast Charger with USB-C & USB-A, Intelligent Chip, Quick Charge & Universal Compatibility",
    slug: "mizazy-135w-super-fast-charger",
    metaTitle: "Mizazy 135W Super Fast Charger | USB-C + USB-A | ₹899",
    metaDescription:
      "Buy Mizazy 135W Super Fast Charger with USB-C and USB-A ports, intelligent chip, fast charging and multiple protection features. Available at an offer price of ₹899.",
    tagline: "135W Max. USB-C + USB-A. Intelligent chip.",
    description:
      "Power your devices quickly and safely with the Mizazy 135W Super Fast Charger. Designed with USB-C and USB-A outputs, an intelligent chip and multiple protection features, this charger is suitable for smartphones and other compatible handheld devices.",
    price: 899,
    mrp: 1299,
    rating: 4.7,
    reviews: 3102,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Front.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790677751/Mizazy_Data_Cable_With_Charger_White.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Front.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Back.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_SIde-Back.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Front1.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790766593/Mizazy_135W_Super_Fast_Charger_Pin-Side.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Front.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Back.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_SIde-Back.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790766592/Mizazy_135W_Super_Fast_Charger_Front1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790766593/Mizazy_135W_Super_Fast_Charger_Pin-Side.png",
      ],
    ],
    badge: "SALE",
    colors: ["#F5F5F5"],
    colorNames: ["White"],
    category: "Mobile Accessories / Chargers",
    features: [
      "135W Max Super Fast Charging",
      "USB-C + USB-A Outputs",
      "Quick Charger",
      "Intelligent Chip",
      "Universal Compatibility",
      "Fast & Safe Charging",
      "Auto Current Detection",
      "Overheat Protection",
      "Overcharging Protection",
      "Short-Circuit Protection",
      "Supports Multiple Fast-Charging Technologies",
      "Compact & Reliable Design",
      "Made in India",
    ],
    keyFeatures: [
      {
        title: "Super Fast Charging",
        text: "Supports high-speed charging with up to 135W maximum power as stated on the product packaging.",
      },
      {
        title: "USB-C + USB-A",
        text: "Equipped with both USB-C and USB-A ports for charging compatible devices.",
      },
      {
        title: "Intelligent Chip",
        text: "The built-in intelligent chip automatically detects the connected compatible device and provides the required charging current.",
      },
      {
        title: "Multiple Protection",
        text: "Designed with protection against overcharging, short circuits and overheating.",
      },
      {
        title: "Universal Compatibility",
        text: "Designed to charge compatible smartphones and handheld electronic devices.",
      },
      {
        title: "Fast & Safe",
        text: "Designed to provide fast, reliable and safe charging for compatible devices.",
      },
      {
        title: "Multi-Protocol Support",
        text: "The packaging indicates compatibility with multiple fast-charging technologies, including:",
        points: ["FlashCharge", "SuperVOOC", "Dart", "Warp Charge", "VOOC", "Dash", "Qualcomm Quick Charge 3.0"],
      },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Description": "All In One Charger",
      "Product Type": "Super Fast Charger",
      Model: "All In One Charger",
      "Maximum Power": "135W Max",
      Input: "AC 100-240V, 50-60Hz, 0.8A",
      "USB Output": "DC 5V / 9V / 12V / 15V - 3A",
      Ports: "USB-C + USB-A",
      "Charging Technology": "Fast Charging",
      Chipset: "Intelligent Chip",
      Protection: "Overcharge, Overheat & Short-Circuit Protection",
      Compatibility: "Compatible with supported smartphones and handheld devices",
      Colour: "White",
      "Country of Origin": "Made in India",
      Quantity: "1 N",
      MRP: "₹1,299",
      Warranty: "As per Mizazy Warranty Policy",
    },
    inBox: ["1 × Mizazy All In One Super Fast Charger", "1 × Fast Charging 1m Cable"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the maximum power of this charger?", a: "The product packaging states a maximum power of 135W." },
      { q: "Does the charger have USB-C and USB-A ports?", a: "Yes. It comes with USB-C and USB-A charging ports." },
      {
        q: "Does it support fast charging?",
        a: "Yes. It is designed as a super fast charger and the packaging indicates compatibility with multiple fast-charging technologies.",
      },
      {
        q: "Is it compatible with different smartphones?",
        a: "Yes. It is designed for universal compatibility with compatible smartphones and handheld electronic devices.",
      },
      { q: "Does it have overheat protection?", a: "Yes. The packaging lists auto-cut and overheat protection." },
      { q: "Does it provide overcharging protection?", a: "Yes. The charger is designed with protection against overcharging." },
      {
        q: "Does it have short-circuit protection?",
        a: "Yes. The product packaging states that the circuit board is designed to protect devices from short circuits.",
      },
      {
        q: "Does it automatically detect the device?",
        a: "Yes. Its intelligent chip automatically detects the connected compatible device and provides the required charging current.",
      },
      { q: "What is the input voltage?", a: "AC 100-240V, 50-60Hz, 0.8A." },
      { q: "What USB output specification is mentioned on the box?", a: "DC 5V / 9V / 12V / 15V - 3A." },
      {
        q: "Is the charging cable included?",
        a: "Yes. The box includes 1 × Fast Charging 1m Cable along with the charger.",
      },
      { q: "What colour is available?", a: "White." },
      {
        q: "Is this a 135W charger?",
        a: 'The packaging markets the charger as "135W Max / 135W Super Fast Charger". Actual charging power depends on the connected device, charging protocol and supported output.',
      },
    ],
    stock: 91,
  },
  {
    id: "hub-pro-7",
    name: "Mizazy 140W Fast Charging Data Cable",
    title:
      "Mizazy 140W Fast Charging Data Cable USB-A to Type-C, 3A Fast Charging, 480Mbps High-Speed Data Sync, 1 Meter Nylon Braided Cable",
    slug: "mizazy-140w-fast-charging-data-cable",
    metaTitle: "Mizazy 140W Fast Charging Data Cable | USB-A to Type-C | ₹379",
    metaDescription:
      "Buy Mizazy 140W Fast Charging Data Cable with USB-A to Type-C connector, up to 3A current, 480Mbps data transfer, 1M nylon braided design and reinforced connectors at ₹379.",
    ogTitle: "Mizazy 140W Fast Charging Data Cable | USB-A to Type-C",
    ogDescription:
      "Mizazy 140W Fast Charging Data Cable with up to 3A current, 480Mbps data transfer, 1M nylon braided design and reinforced connectors. Get it at ₹379.",
    imageAlt: "Mizazy 140W Fast Charging USB-A to Type-C Data Cable",
    imageTitle: "Mizazy 140W Fast Charging Data Cable",
    seoKeywords: [
      "Mizazy data cable",
      "Mizazy Type-C cable",
      "140W fast charging cable",
      "USB-A to Type-C cable",
      "Type-C data cable",
      "fast charging data cable",
      "3A charging cable",
      "480Mbps data cable",
      "nylon braided Type-C cable",
      "1 meter Type-C cable",
      "USB-A Type-C fast charging cable",
      "Mizazy",
      "Data Cable",
      "Type-C Cable",
      "USB-A to Type-C",
      "Fast Charging Cable",
      "140W Cable",
      "3A Cable",
      "480Mbps Data Cable",
      "Nylon Braided Cable",
      "Mobile Accessories",
    ],
    tagline: "140W Fast Charging | USB-A to Type-C | 480Mbps | 1M Nylon Braided",
    tags: ["140W Fast Charging", "480Mbps Data Sync", "1M Length", "Nylon Braided", "USB-A to Type-C"],
    description:
      "Experience fast charging and high-speed data transfer with the Mizazy 140W Fast Charging Data Cable. Featuring a USB-A to Type-C connector, up to 3A current support, data transfer speeds of up to 480Mbps, a premium nylon braided design and reinforced connectors, this 1-meter cable is designed for everyday charging and data synchronization with compatible Type-C devices.",
    price: 379,
    mrp: 499,
    rating: 4.5,
    reviews: 1847,
    image:
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable2.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790600382/Mizazy_Data_Cable.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable2.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable1.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780501/Mizazy_140W_Fast_Charging_Data_Cable.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable2.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780501/Mizazy_140W_Fast_Charging_Data_Cable.png",
      ],
    ],
    badge: undefined,
    colors: ["#111111"],
    colorNames: ["Black"],
    category: "Mobile Accessories / Cables",
    features: [
      "140W Fast Charging",
      "USB-A to Type-C",
      "Up to 3A Current Support",
      "Up to 480Mbps Data Transfer",
      "1 Meter Cable Length",
      "Premium Nylon Braided Cable",
      "Tangle-Free Design",
      "Knot-Resistant Design",
      "Reinforced Connectors",
      "Fast Charging Support",
      "High-Speed Data Sync",
      "Compatible with Type-C Devices",
      "Durable Build",
      "Black Colour",
    ],
    keyFeatures: [
      {
        title: "140W Fast Charging",
        text: "The product packaging highlights support for 140W fast charging. Actual charging speed depends on the connected charger, device and supported charging protocol.",
      },
      { title: "Up to 3A Current", text: "The packaging specifies current support of up to 3A." },
      {
        title: "USB-A to Type-C Connectors",
        text: "The cable features a USB-A connector on one end and a Type-C connector on the other.",
      },
      {
        title: "High-Speed Data Transfer",
        text: "Supports data transfer speeds of up to 480Mbps as specified on the product packaging.",
      },
      {
        title: "Premium Nylon Braided Design",
        text: "The cable uses a nylon braided construction designed for improved durability and everyday use.",
      },
      {
        title: "Tangle-Free & Knot-Resistant",
        text: "The packaging highlights a tangle-free and knot-resistant design for convenient handling.",
      },
      {
        title: "Reinforced Connectors",
        text: "Reinforced connectors are designed to provide improved durability during regular use.",
      },
      {
        title: "1-Meter Length",
        text: "The cable has a length of 1 meter, suitable for everyday charging and data synchronization.",
      },
      {
        title: "Fast Charging & Data Sync",
        text: "Designed to support both charging and high-speed data synchronization with compatible devices.",
      },
      { title: "Wide Type-C Compatibility", text: "The packaging states compatibility with Type-C devices." },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "Data Cable",
      Model: "Data Cable",
      "Product Type": "Fast Charging Data Cable",
      Subcategory: "USB-A to Type-C Cable",
      "Connector Type": "USB-A to Type-C",
      "Maximum Charging Power": "140W",
      Current: "Up to 3A",
      "Data Transfer Speed": "Up to 480Mbps",
      "Cable Length": "1 Meter",
      "Cable Material": "Nylon Braided",
      Design: "Tangle-Free / Knot-Resistant",
      "Connector Design": "Reinforced Connectors",
      Function: "Charging + Data Sync",
      Compatibility: "Type-C Devices",
      Colour: "Black",
      "Country of Origin": "India",
      "Manufacturing Year": "2026",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    infoSections: [
      {
        title: "Charging Information",
        items: [
          { label: "Maximum Charging Power", value: "140W" },
          { label: "Maximum Current", value: "Up to 3A" },
        ],
        notes: [
          "The packaging highlights 140W fast charging support and up to 3A current.",
          "Actual charging speed depends on the connected charger, smartphone/device, charging protocol and other hardware limitations.",
        ],
      },
      {
        title: "Data Transfer Information",
        items: [
          { label: "Data Transfer Speed", value: "Up to 480Mbps" },
          { label: "Function", value: "Charging + Data Sync" },
        ],
        notes: [
          "Actual data transfer speed depends on the connected device, port, storage device and other hardware/software conditions.",
        ],
      },
    ],
    inBox: ["1 × Mizazy 140W Fast Charging USB-A to Type-C Data Cable"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy 140W Fast Charging Data Cable." },
      { q: "What type of cable is this?", a: "It is a USB-A to Type-C fast charging data cable." },
      { q: "What is the maximum charging power?", a: "The packaging highlights up to 140W fast charging support." },
      { q: "Does the cable support 3A current?", a: "Yes. The packaging specifies current support of up to 3A." },
      {
        q: "What is the data transfer speed?",
        a: "The cable supports data transfer speeds of up to 480Mbps as specified on the packaging.",
      },
      { q: "What is the length of the cable?", a: "The cable is 1 meter long." },
      { q: "What material is the cable made from?", a: "The cable features a nylon braided construction." },
      { q: "Is the cable tangle-free?", a: "The packaging highlights a tangle-free and knot-resistant design." },
      { q: "Are the connectors reinforced?", a: "Yes. Reinforced connectors are listed as a product feature." },
      {
        q: "Which devices are compatible with this cable?",
        a: "It is designed for compatible Type-C devices that support USB-A to Type-C connections.",
      },
      {
        q: "Can this cable be used for data transfer?",
        a: "Yes. It supports charging and data synchronization with data transfer speeds of up to 480Mbps.",
      },
      {
        q: "Does the cable support 140W charging on every device?",
        a: "No. Actual charging speed depends on the connected charger, device and supported charging protocol.",
      },
      {
        q: "Is the charger included?",
        a: "No. The product listing is for the data cable only. A compatible charger/power adapter is required separately.",
      },
      { q: "What colour is available?", a: "Black." },
      { q: "What is the MRP?", a: "The MRP is ₹499." },
      { q: "What is the offer price?", a: "The offer price is ₹379." },
      { q: "How much can I save?", a: "You save ₹120 compared with the listed MRP." },
      { q: "What is included in the box?", a: "1 × Mizazy 140W Fast Charging USB-A to Type-C Data Cable." },
    ],
    emi: undefined,
    stock: 41,
  },
  {
    id: "powerslim-20k",
    name: "Mizazy Equalizer Bluetooth Neckband",
    title:
      "Mizazy Equalizer Bluetooth Neckband Earphones with 100H Playtime, 13mm Driver, Magnetic Earbuds, Type-C Charging & HD Stereo Sound",
    slug: "mizazy-equalizer-bluetooth-neckband",
    metaTitle: "Mizazy Equalizer Bluetooth Neckband | 100H Playtime | ₹999",
    metaDescription:
      "Buy Mizazy Equalizer Bluetooth Neckband with 100H playtime, 13mm drivers, Bluetooth 5.2, magnetic earbuds, Type-C charging and HD stereo sound at ₹999.",
    tagline: "100H playtime. 13mm drivers. Bluetooth 5.2.",
    description:
      "Enjoy immersive music and convenient calling with the Mizazy Equalizer Bluetooth Neckband. Featuring up to 100 hours of playtime, magnetic earbuds, Type-C charging, HD stereo sound, 13mm drivers and an in-built microphone, it is designed for everyday music, calls and entertainment.",
    price: 999,
    mrp: 1499,
    rating: 4.6,
    reviews: 4291,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790765790/Mizazy_Equalizer_Bluetooth_Neckband_Black1.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790683817/Mizazy_Blue_Neckband.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790765790/Mizazy_Equalizer_Bluetooth_Neckband_Black1.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790765792/Mizazy_Equalizer_Bluetooth_Neckband_Black2.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790765792/Mizazy_Equalizer_Bluetooth_Neckband_Black.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765790/Mizazy_Equalizer_Bluetooth_Neckband_Black1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765792/Mizazy_Equalizer_Bluetooth_Neckband_Black2.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765792/Mizazy_Equalizer_Bluetooth_Neckband_Black.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765791/Mizazy_Equalizer_Bluetooth_Neckband_Blue1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765794/Mizazy_Equalizer_Bluetooth_Neckband_Blue.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765800/Mizazy_Equalizer_Bluetooth_Neckband_Blue2.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765793/Mizazy_Equalizer_Bluetooth_Neckband_Green1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765793/Mizazy_Equalizer_Bluetooth_Neckband_Green.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765794/Mizazy_Equalizer_Bluetooth_Neckband_Green2.png",
      ],
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765794/Mizazy_Equalizer_Bluetooth_Neckband_Orange2.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765794/Mizazy_Equalizer_Bluetooth_Neckband_Orange1.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790765806/Mizazy_Equalizer_Bluetooth_Neckband_Orange.png",
      ],
    ],
    badge: "BEST SELLER",
    colors: ["#111111", "#1E4FA8", "#1F7A4D", "#F07C1E"],
    colorNames: ["Black", "Blue", "Green", "Orange"],
    category: "Audio / Bluetooth Neckband",
    features: [
      "Up to 100 Hours Playtime",
      "13mm Dynamic Drivers",
      "HD Stereo Sound",
      "Bluetooth 5.2",
      "Type-C Charging",
      "Magnetic Earbuds",
      "Built-in Microphone",
      "In-Line Controls",
      "Dust, Water & Sweat Resistant",
      "Voice Changer Feature",
      "Lightweight Design",
      "Comfortable & Easy to Wear",
      "EQ Feature",
      "Anti-Lose Magnetic Design",
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "Equalizer",
      "Product Type": "Bluetooth Neckband",
      Model: "Equalizer",
      "Bluetooth Version": "5.2",
      "Driver Size": "13mm",
      Playtime: "Up to 100 Hours",
      "Charging Port": "Type-C",
      Sound: "HD Stereo Sound",
      Microphone: "Built-in Microphone",
      Controls: "In-Line Control",
      Earbuds: "Magnetic",
      "Voice Changer": "Yes",
      "EQ Feature": "Yes",
      "Water/Sweat Resistance": "Dust, Water & Sweat Resistant",
      Design: "Lightweight & Comfortable",
      Colours: "Black, Blue, Green, Orange",
      "Net Quantity": "1 N.O.S.",
      Warranty: "As per Mizazy Warranty Policy",
    },
    inBox: [
      "1 × Mizazy Equalizer Bluetooth Neckband",
      "Charging accessories included with the actual product package",
      "User documentation, if included",
    ],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "Is this neckband wireless?", a: "Yes. Mizazy Equalizer is a Bluetooth wireless neckband." },
      { q: "What is the Bluetooth version?", a: "Bluetooth Version 5.2." },
      {
        q: "How long is the playtime?",
        a: "The packaging claims up to 100 hours of playtime. Actual battery life may vary depending on volume and usage.",
      },
      { q: "Does it support Type-C charging?", a: "Yes, it supports Type-C charging." },
      { q: "Does it have a microphone?", a: "Yes, it has an in-built microphone." },
      { q: "What size are the drivers?", a: "It features 13mm drivers." },
      { q: "Does it have magnetic earbuds?", a: "Yes, the earbuds feature a magnetic design." },
      { q: "Is it suitable for calls?", a: "Yes, it has an in-built microphone and in-line controls for calling." },
      {
        q: "Is it water and sweat resistant?",
        a: "The packaging states that the product is dust, water and sweat resistant. Avoid intentional submersion in water.",
      },
      { q: "What colours are available?", a: "Black, Blue, Green and Orange." },
      { q: "Does it have a voice changer?", a: "Yes, Voice Changer is listed as a product feature." },
      {
        q: "Is it comfortable for long use?",
        a: "The product is designed to be lightweight, easy to wear and comfortable.",
      },
    ],
    stock: 64,
  },
  {
    id: "desklamp-pro",
    name: "Mizazy 65W Fast USB Data Cable",
    title: "Mizazy 65W Fast USB Data Cable USB-A to Type-C, Fast Charging, USB 2.0 Data Sync, Durable Build",
    slug: "mizazy-65w-fast-usb-data-cable",
    metaTitle: "Mizazy 65W Fast USB Data Cable | USB-A to Type-C | ₹349",
    metaDescription:
      "Buy Mizazy 65W Fast USB Data Cable with USB-A to Type-C connectivity, fast charging support, USB 2.0 data sync and durable build at ₹349.",
    ogTitle: "Mizazy 65W Fast USB Data Cable | USB-A to Type-C",
    ogDescription:
      "Mizazy 65W Fast USB Data Cable with USB-A to Type-C connectivity, fast charging support, USB 2.0 data sync and durable build. Get it at ₹349.",
    imageAlt: "Mizazy 65W Fast USB-A to Type-C Data Cable",
    imageTitle: "Mizazy 65W Fast USB Data Cable",
    seoKeywords: [
      "Mizazy data cable",
      "Mizazy Type-C cable",
      "Mizazy USB cable",
      "65W data cable",
      "65W fast charging cable",
      "USB-A to Type-C cable",
      "Type-C fast charging cable",
      "fast charging data cable",
      "USB 2.0 data cable",
      "USB-A to Type-C data cable",
      "Mizazy USB-A to Type-C",
      "Mizazy",
      "Data Cable",
      "Type-C Cable",
      "USB-A to Type-C",
      "65W Cable",
      "Fast Charging Cable",
      "USB 2.0",
      "Data Sync",
      "Mobile Accessories",
    ],
    tagline: "65W Max Output | Fast Charging | USB 2.0 | USB-A to Type-C",
    tags: ["65W Max Output", "Fast Charging", "USB 2.0", "Data Sync"],
    description:
      "Experience fast and reliable charging with the Mizazy 65W Fast USB Data Cable. Designed with USB-A to Type-C connectivity, fast charging support, USB 2.0 data transfer and a durable build, this cable is suitable for compatible smartphones, tablets and other Type-C devices.",
    price: 349,
    mrp: 499,
    rating: 4.6,
    reviews: 892,
    image:
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780082/Mizazy_65W_Fast_USB_Data_Cable.png",
    video: "https://res.cloudinary.com/aiwtovua/video/upload/v1790709749/Mizazy_White_Cable.mp4",
    images: [
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780082/Mizazy_65W_Fast_USB_Data_Cable.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780083/Mizazy_65W_Fast_USB_Data_Cable2.png",
      "https://res.cloudinary.com/aiwtovua/image/upload/v1790780101/Mizazy_65W_Fast_USB_Data_Cable1.png",
    ],
    colorImages: [
      [
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780082/Mizazy_65W_Fast_USB_Data_Cable.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780083/Mizazy_65W_Fast_USB_Data_Cable2.png",
        "https://res.cloudinary.com/aiwtovua/image/upload/v1790780101/Mizazy_65W_Fast_USB_Data_Cable1.png",
      ],
    ],
    badge: "NEW",
    isNew: true,
    colors: ["#F5F5F5"],
    colorNames: ["White"],
    category: "Mobile Accessories / Cables",
    features: [
      "65W Max Output",
      "Fast Charging",
      "USB-A to Type-C",
      "USB 2.0",
      "Data Sync",
      "Durable Build",
      "Wide Compatibility",
      "Premium Quality",
      "Designed for Everyday Use",
    ],
    keyFeatures: [
      {
        title: "65W Max Output",
        text: "The product packaging highlights a maximum output of up to 65W. Actual charging speed depends on the connected charger, device and supported charging technology.",
      },
      { title: "Fast Charging", text: "The cable is designed to support fast charging with compatible devices and chargers." },
      {
        title: "USB-A to Type-C",
        text: "The cable features a USB-A connector on one end and a Type-C connector on the other.",
      },
      {
        title: "USB 2.0 Data Support",
        text: "The packaging highlights USB 2.0 support for compatible data transfer and synchronization.",
      },
      { title: "Data Cable", text: "The cable supports both charging and data transfer with compatible devices." },
      { title: "Durable Build", text: "The cable is designed for regular everyday charging and data synchronization." },
      {
        title: "Wide Compatibility",
        text: "Designed for compatible Type-C devices including smartphones, tablets and other supported devices.",
      },
      {
        title: "Premium Quality",
        text: "The product packaging highlights a premium-quality build for everyday usage.",
      },
    ],
    specs: {
      Brand: "Mizazy",
      "Product Name": "Fast USB Data Cable",
      Model: "Fast USB Data Cable",
      "Product Type": "USB Data Cable",
      Subcategory: "USB-A to Type-C Cable",
      "Connector Type": "USB-A to Type-C",
      "Maximum Output": "65W Max",
      "Data Standard": "USB 2.0",
      Function: "Charging + Data Sync",
      "Cable Type": "USB-A to Type-C",
      Colour: "White",
      Compatibility: "Compatible Type-C Devices",
      Quantity: "1 Unit",
      Warranty: "As per Mizazy Warranty Policy",
    },
    infoSections: [
      {
        title: "Charging Information",
        items: [
          { label: "Maximum Output", value: "65W Max" },
          { label: "Charging", value: "Fast Charging Support" },
        ],
        notes: [
          "The packaging states 65W maximum output.",
          "Actual charging speed depends on the connected charger, device, charging protocol and hardware limitations.",
        ],
      },
      {
        title: "Data Transfer Information",
        items: [
          { label: "Data Standard", value: "USB 2.0" },
          { label: "Function", value: "Data Sync" },
        ],
        notes: ["The cable supports data synchronization with compatible devices."],
      },
    ],
    inBox: ["1 × Mizazy 65W Fast USB Data Cable USB-A to Type-C"],
    warranty: "Warranty: As per Mizazy Warranty Policy",
    faqs: [
      { q: "What is the product name?", a: "The product is Mizazy 65W Fast USB Data Cable." },
      { q: "What type of cable is this?", a: "It is a USB-A to Type-C fast charging data cable." },
      { q: "What is the maximum output of the cable?", a: "The packaging highlights a maximum output of up to 65W." },
      {
        q: "Does the cable support fast charging?",
        a: "Yes. The cable supports fast charging with compatible devices and chargers.",
      },
      { q: "Does the cable support data transfer?", a: "Yes. It supports data synchronization through USB 2.0." },
      {
        q: "What type of connectors does it have?",
        a: "It has a USB-A connector on one end and a Type-C connector on the other.",
      },
      { q: "What is the data standard?", a: "The packaging specifies USB 2.0." },
      { q: "What colour is the cable?", a: "The available cable colour is White." },
      {
        q: "Is the charger included?",
        a: "No. The product listing is for the data cable only. A compatible charger/power adapter is required separately.",
      },
      {
        q: "Which devices can use this cable?",
        a: "It can be used with compatible Type-C devices such as smartphones, tablets and other supported devices.",
      },
      {
        q: "Does every device support 65W charging with this cable?",
        a: "No. Actual charging speed depends on the device, charger and supported charging technology.",
      },
      { q: "Does it support data synchronization?", a: "Yes. The cable supports data synchronization through USB 2.0." },
      { q: "What is the MRP?", a: "The MRP is ₹499." },
      { q: "What is the offer price?", a: "The offer price is ₹349." },
      { q: "How much can I save?", a: "You save ₹150 compared with the listed MRP." },
      { q: "What is included in the box?", a: "1 × Mizazy 65W Fast USB Data Cable USB-A to Type-C." },
    ],
    emi: undefined,
    stock: 38,
  },
];

export const categories = [
  {
    name: "Earbuds",
    image: "https://res.cloudinary.com/aiwtovua/video/upload/v1790597307/Mizazy_Black_Earbuds_video.mp4",
    count: 5,
  },
  {
    name: "Neckband",
    image: "https://res.cloudinary.com/aiwtovua/video/upload/v1790601355/Mizazy_Neckband_Orange.mp4",
    count: 4,
  },
  {
    name: "Android and iPhone Charger",
    image: "https://res.cloudinary.com/aiwtovua/video/upload/v1790599340/Mizazy_Charger_Android.mp4",
    count: 2,
  },
  {
    name: "Data Cable",
    image: "https://res.cloudinary.com/aiwtovua/video/upload/v1790600382/Mizazy_Data_Cable.mp4",
    count: 3,
  },
];

export const reviews = [
  {
    name: "Arjun Sharma",
    location: "Mumbai",
    rating: 5,
    date: "Sep 2026",
    product: "Mizazy Wireless Buds 104",
    productId: "buds-pro",
    review: "Paired instantly with my Android phone through Google Fast Pairing. Calls are clear thanks to the quad mic, and the case keeps them going for days. Taking one bud out pauses the music — very handy.",
    verified: true,
    helpful: 847,
    avatar: "AS",
  },
  {
    name: "Priya Nair",
    location: "Bangalore",
    rating: 5,
    date: "Aug 2026",
    product: "Mizazy Equalizer Bluetooth Neckband",
    productId: "powerslim-20k",
    review: "Battery life is unreal — I charge it maybe once a week. Bass from the 13mm drivers is punchy, and the magnetic earbuds snap together so they never tangle. Survived my sweaty gym sessions without any issue.",
    verified: true,
    helpful: 612,
    avatar: "PN",
  },
  {
    name: "Rahul Mehta",
    location: "Delhi",
    rating: 5,
    date: "Sep 2026",
    product: "Mizazy Buds X Prime",
    productId: "soundmax-pro",
    review: "Bought the green one and it looks premium in hand. Very lightweight, so I forget I'm wearing them on long metro rides. Sound is clear and the battery with the case easily lasts my whole week.",
    verified: true,
    helpful: 489,
    avatar: "RM",
  },
  {
    name: "Sneha Reddy",
    location: "Hyderabad",
    rating: 5,
    date: "Sep 2026",
    product: "Mizazy 20W USB-C Power Adapter for iPhone",
    productId: "neckpro",
    review: "Works perfectly with my iPhone using a USB-C to Lightning cable — fast charging kicks in right away. Small enough to keep in my handbag and it doesn't heat up. Great value compared to the original.",
    verified: true,
    helpful: 356,
    avatar: "SR",
  },
  {
    name: "Karthik Rajan",
    location: "Chennai",
    rating: 5,
    date: "Aug 2026",
    product: "Mizazy 135W Super Fast Charger",
    productId: "gan-65w",
    review: "Having both USB-C and USB-A ports means I charge my phone and my wife's phone together. Charging is noticeably faster than my old adapter, and the 1m cable in the box is a nice bonus.",
    verified: true,
    helpful: 723,
    avatar: "KR",
  },
  {
    name: "Anjali Desai",
    location: "Pune",
    rating: 4,
    date: "Jul 2026",
    product: "Mizazy 140W Fast Charging Data Cable",
    productId: "hub-pro-7",
    review: "The nylon braiding feels really strong and doesn't tangle in my bag. Fast charging works well with my phone and file transfer to the laptop is quick. Would love a 2m option too.",
    verified: true,
    helpful: 284,
    avatar: "AD",
  },
  {
    name: "Vikram Singh",
    location: "Jaipur",
    rating: 5,
    date: "Aug 2026",
    product: "Mizazy 120W Fast USB Data Cable",
    productId: "watch-x1",
    review: "Solid metallic connectors and a thick cable — feels like it will last. Charges my phone fast with my existing charger and the connection never drops. Good buy at this price.",
    verified: true,
    helpful: 198,
    avatar: "VS",
  },
  {
    name: "Meera Iyer",
    location: "Kochi",
    rating: 4,
    date: "Sep 2026",
    product: "Mizazy 65W Fast USB Data Cable",
    productId: "desklamp-pro",
    review: "Clean white finish that matches my charger. Fast charging works on my Type-C phone and I use it daily for syncing photos to my PC. Simple, reliable everyday cable.",
    verified: true,
    helpful: 167,
    avatar: "MI",
  },
  {
    name: "Rohan Gupta",
    location: "Kolkata",
    rating: 5,
    date: "Sep 2026",
    product: "Mizazy Wireless Buds 104",
    productId: "buds-pro",
    review: "Got the white pair as a gift for my sister and ended up buying the blue one for myself. Fit is comfortable for hours, sound is crisp, and environmental noise cancellation makes calls on busy roads clear.",
    verified: true,
    helpful: 241,
    avatar: "RG",
  },
];

export const bundles = [
  {
    title: "Audio Essentials",
    subtitle: "Wireless Buds 104 + 20W USB-C Adapter",
    products: ["buds-pro", "neckpro"],
    discount: 15,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790761958/Mizazy_Earbuds_104_White_Front.png",
    tag: "Coming Soon",
  },
  {
    title: "Power Traveler",
    subtitle: "Equalizer Neckband + 135W Charger",
    products: ["powerslim-20k", "gan-65w"],
    discount: 18,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790765793/Mizazy_Equalizer_Bluetooth_Neckband_Green1.png",
    tag: "Coming Soon",
  },
  {
    title: "Charge & Sync Duo",
    subtitle: "140W + 65W Data Cables",
    products: ["hub-pro-7", "desklamp-pro"],
    discount: 20,
    image: "https://res.cloudinary.com/aiwtovua/image/upload/v1790780496/Mizazy_140W_Fast_Charging_Data_Cable2.png",
    tag: "Coming Soon",
  },
];

export const coupons = [{ code: "MIZAZY10", discountPercent: 10, active: true }];
