export const products = [
  {
    id: "buds-pro",
    name: "MIZAZY Buds Pro",
    tagline: "True wireless. Unreal sound.",
    description:
      "Experience the future of audio with 40dB hybrid ANC, 30-hour total battery, and Hi-Res audio certification. The MIZAZY Buds Pro are engineered for those who refuse to compromise.",
    price: 2499,
    mrp: 3999,
    rating: 4.8,
    reviews: 2847,
    image:
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&h=800&fit=crop&auto=format&q=85",
    images: [
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1578319439584-104c94d37305?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&h=800&fit=crop&auto=format&q=85",
    ],
    badge: "BEST SELLER",
    colors: ["#E8E8E8", "#111111", "#1E3A6E"],
    colorNames: ["Frost White", "Midnight Black", "Deep Blue"],
    category: "Audio",
    features: [
      "40dB Hybrid Active Noise Cancellation",
      "30 hours total battery (8h ANC on + case)",
      "Transparency mode for ambient awareness",
      "IPX4 splash & sweat resistance",
      "Multipoint: connect 2 devices simultaneously",
      "Fast charge: 10 min → 2 hours playback",
      "Hi-Res Audio + LDAC codec support",
      "Touch controls with custom gestures",
    ],
    specs: {
      "Driver Size": "11mm Dynamic",
      "Frequency Response": "20Hz – 20kHz",
      "Battery (Buds)": "8h (ANC on) / 12h (ANC off)",
      "Battery (Case)": "30h total / wireless charging",
      Connectivity: "Bluetooth 5.3 + Multipoint",
      Codecs: "LDAC, AAC, SBC",
      "Water Resistance": "IPX4",
      Microphones: "4× beamforming mics",
      Weight: "5.8g per bud / 48g case",
      Warranty: "1 Year",
    },
    inBox: [
      "MIZAZY Buds Pro (Left + Right)",
      "Wireless Charging Case",
      "USB-C Cable (25cm)",
      "Ear Tips — S, M, L sizes",
      "Quick Start Guide",
    ],
    emi: "EMI from ₹209/month",
    stock: 48,
  },
  {
    id: "watch-x1",
    name: "MIZAZY Watch X1",
    tagline: "Your health, always on.",
    description:
      'A 1.96" AMOLED display meets advanced health intelligence. Track ECG, SpO2, sleep, stress, and 100+ workouts with 7-day battery. Built for the everyday achiever.',
    price: 4999,
    mrp: 7999,
    rating: 4.7,
    reviews: 1523,
    image:
      "https://images.unsplash.com/photo-1772949399808-7020b02896b9?w=800&h=800&fit=crop&auto=format&q=85",
    images: [
      "https://images.unsplash.com/photo-1772949399808-7020b02896b9?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1783792894893-8332ee93d1de?w=800&h=800&fit=crop&auto=format&q=85",
    ],
    badge: "NEW",
    colors: ["#1a1a1a", "#2D3F5A", "#5C3A1E"],
    colorNames: ["Graphite", "Ocean Blue", "Mocha"],
    category: "Smart Gadgets",
    isNew: true,
    features: [
      '1.96" AMOLED Always-On Display (410×502px)',
      "ECG + SpO2 + Body Temperature sensors",
      "7-day battery / 14-day lite mode",
      "100+ built-in workout modes + auto-detect",
      "GPS + GLONASS + Beidou built-in",
      "5ATM water resistance (pool-safe)",
      "Bluetooth calls + voice assistant",
      "Menstrual & sleep cycle tracking",
    ],
    specs: {
      Display: "1.96\" AMOLED, Always-On, 60Hz",
      Battery: "500mAh / 7 days typical",
      "Water Rating": "5ATM (50m)",
      Sensors: "Heart rate, SpO2, ECG, Temp, Gyro",
      GPS: "GPS + GLONASS + Beidou",
      Connectivity: "Bluetooth 5.2 + WiFi 2.4GHz",
      Strap: "22mm quick-release",
      Charging: "Magnetic USB-C, 2h full charge",
      Warranty: "1 Year",
    },
    inBox: ["MIZAZY Watch X1", "Magnetic Charging Cable", "Extra Strap (Large)", "Documentation"],
    emi: "EMI from ₹417/month",
    stock: 32,
  },
  {
    id: "soundmax-pro",
    name: "MIZAZY SoundMax Pro",
    tagline: "Studio-grade. Anywhere.",
    description:
      "50mm premium drivers with MIZAZY's signature EQ tuning. 45dB hybrid ANC, 60-hour battery, and LDAC Hi-Res Audio. The headphones that sound like a studio, feel like silence.",
    price: 3499,
    mrp: 5999,
    rating: 4.9,
    reviews: 986,
    image:
      "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&h=800&fit=crop&auto=format&q=85",
    images: [
      "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=800&h=800&fit=crop&auto=format&q=85",
    ],
    colors: ["#111111", "#E8E8E8", "#C8A96E"],
    colorNames: ["Midnight", "Arctic White", "Gold Edition"],
    category: "Audio",
    features: [
      "50mm premium dynamic drivers with MIZAZY tuning",
      "45dB Hybrid ANC + Transparency mode",
      "60 hours playback / 80h without ANC",
      "LDAC Hi-Res Audio certified",
      "Multi-point: 3 devices simultaneously",
      "Foldable design with carry case",
      "Wired mode: 3.5mm + USB-C",
      "Companion app with custom EQ",
    ],
    specs: {
      Driver: "50mm Dynamic",
      ANC: "Hybrid 45dB reduction",
      Battery: "60h (ANC) / 80h (off)",
      Codecs: "LDAC, aptX HD, AAC, SBC",
      Weight: "285g",
      Foldable: "Yes",
      Microphones: "4× beamforming mics",
      Wired: "3.5mm + USB-C",
      Warranty: "1 Year",
    },
    inBox: [
      "MIZAZY SoundMax Pro",
      "Premium Carry Case",
      "USB-C Cable (1.2m)",
      "3.5mm Aux Cable (1.2m)",
      "Airplane Adapter",
    ],
    emi: "EMI from ₹292/month",
    stock: 27,
  },
  {
    id: "powerslim-20k",
    name: "MIZAZY PowerSlim 20K",
    tagline: "Ultra-thin. Maximum power.",
    description:
      "20,000mAh at just 13mm thin. Three simultaneous outputs — charge your phone, laptop, and tablet at once. BIS certified and airline-safe.",
    price: 1799,
    mrp: 2999,
    rating: 4.6,
    reviews: 4291,
    image:
      "https://images.unsplash.com/photo-1644571669401-9ab344866592?w=800&h=800&fit=crop&auto=format&q=85",
    images: [
      "https://images.unsplash.com/photo-1644571669401-9ab344866592?w=800&h=800&fit=crop&auto=format&q=85",
      "https://images.unsplash.com/photo-1557767382-97b28f5488e7?w=800&h=800&fit=crop&auto=format&q=85",
    ],
    badge: "BEST SELLER",
    colors: ["#111111", "#E8E8E8", "#1E3D2A"],
    colorNames: ["Graphite", "Pearl White", "Forest Green"],
    category: "Power",
    features: [
      "20,000mAh at only 13mm thin",
      "65W USB-C Power Delivery (laptop charging)",
      "Charge 3 devices simultaneously",
      "72W combined max output",
      "LED battery indicator (4-level)",
      "BIS certified + airline safe",
      "Charges MacBook Air in ~90 minutes",
      "Low-power charging mode for earbuds",
    ],
    specs: {
      Capacity: "20,000mAh (74Wh)",
      "Input (USB-C)": "65W PD",
      "Output 1 (USB-C)": "65W PD",
      "Output 2 (USB-C)": "45W PD",
      "Output 3 (USB-A)": "18W QC 3.0",
      Thickness: "13mm",
      Weight: "386g",
      Certification: "BIS, CE, FCC, RoHS",
    },
    inBox: ["MIZAZY PowerSlim 20K", "USB-C to USB-C Cable (1m)", "Premium Travel Pouch"],
    emi: "EMI from ₹150/month",
    stock: 64,
  },
  {
    id: "gan-65w",
    name: "MIZAZY GaN 65W",
    tagline: "Tiny charger. Big power.",
    description:
      "GaN III technology packs 65W into a charger 65% smaller than traditional adapters. Three ports. One charger. Every device.",
    price: 1299,
    mrp: 1999,
    rating: 4.7,
    reviews: 3102,
    image: "https://images.unsplash.com/photo-1601524909162-ae8725290836?w=800&h=800&fit=crop&auto=format",
    images: ["https://images.unsplash.com/photo-1601524909162-ae8725290836?w=800&h=800&fit=crop&auto=format"],
    badge: "SALE",
    colors: ["#111111", "#E8E8E8"],
    colorNames: ["Midnight Black", "Chalk White"],
    category: "Power",
    features: [
      "GaN III — 65% smaller than standard chargers",
      "Dual USB-C (65W + 45W) + USB-A 18W",
      "Smart power sharing — auto-distributes watts",
      "Universal voltage 100–240V",
      "Foldable pins for easy travel",
      "Charges MacBook Air + iPhone + AirPods simultaneously",
    ],
    specs: {
      Technology: "GaN III",
      "Total Output": "65W max",
      "Port 1 (USB-C)": "65W PD 3.0",
      "Port 2 (USB-C)": "45W PD",
      "Port 3 (USB-A)": "18W QC 3.0",
      Input: "100–240V AC",
      Weight: "89g",
      Dimensions: "48 × 48 × 30mm",
    },
    inBox: ["MIZAZY GaN 65W Charger"],
    stock: 91,
  },
  {
    id: "hub-pro-7",
    name: "MIZAZY HubPro 7-in-1",
    tagline: "One hub for everything.",
    description:
      "Aerospace-grade aluminum. 4K@60Hz HDMI, 100W PD, dual USB 3.0, SD + microSD. Plug in and your desk transforms.",
    price: 2199,
    mrp: 3499,
    rating: 4.5,
    reviews: 1847,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=800&fit=crop&auto=format",
    images: ["https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&h=800&fit=crop&auto=format"],
    colors: ["#B8B8B8", "#111111"],
    colorNames: ["Silver", "Space Gray"],
    category: "Desk Setup",
    features: [
      "4K@60Hz HDMI output",
      "2× USB-A 3.0 (5Gbps)",
      "USB-C 100W passthrough charging",
      "SD + MicroSD card reader (UHS-I)",
      "3.5mm combo audio jack",
      "No drivers required — plug & play",
      "Aluminum body with passive heat dissipation",
      "18cm flexible cable",
    ],
    specs: {
      HDMI: "4K@60Hz / 1080p@144Hz",
      "USB-A": "2× USB 3.0 (5Gbps)",
      "USB-C PD": "100W passthrough",
      "Card Reader": "SD + MicroSD (UHS-I, 104MB/s)",
      Audio: "3.5mm combo (in/out)",
      "Cable Length": "18cm",
      Material: "Aerospace Aluminum",
      Compatibility: "Mac, Windows, iPad Pro, ChromeOS",
    },
    inBox: ["MIZAZY HubPro 7-in-1"],
    stock: 41,
  },
  {
    id: "neckpro",
    name: "MIZAZY NeckPro",
    tagline: "Comfort. Clarity. All day.",
    description:
      "24-hour battery in a neckband that weighs just 22g. Magnetic earpieces, IPX5 resistance, and HD voice calling for the always-on professional.",
    price: 999,
    mrp: 1799,
    rating: 4.4,
    reviews: 5623,
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=800&fit=crop&auto=format",
    images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&h=800&fit=crop&auto=format"],
    badge: "LIMITED",
    colors: ["#111111", "#C8A96E", "#E8E8E8"],
    colorNames: ["Jet Black", "Gold", "Pearl"],
    category: "Audio",
    features: [
      "Magnetic earpiece auto-play/pause",
      "24-hour battery life",
      "HD Voice calling (CVC 8.0 noise cancellation)",
      "IPX5 sweat & splash resistant",
      "Quick charge: 10 min → 3 hours",
      "Memory foam ear tips (3 sizes)",
      "Flexible flat-cable neckband design",
    ],
    specs: {
      Driver: "10mm dynamic",
      Battery: "24h playback",
      "Water Rating": "IPX5",
      Connectivity: "Bluetooth 5.0",
      Microphone: "Dual mic CVC 8.0",
      Weight: "22g",
      Warranty: "6 Months",
    },
    inBox: ["MIZAZY NeckPro", "USB-C Charging Cable", "Ear Tips — S, M, L", "User Manual"],
    stock: 73,
  },
  {
    id: "desklamp-pro",
    name: "MIZAZY DeskLamp Pro",
    tagline: "Light designed for focus.",
    description:
      "Eye-care flicker-free LED with 5 brightness levels and 3 color temperatures. A 360° arm, USB charging port, and design that belongs on any premium desk.",
    price: 1599,
    mrp: 2499,
    rating: 4.6,
    reviews: 892,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&h=800&fit=crop&auto=format",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&h=800&fit=crop&auto=format"],
    badge: "NEW",
    isNew: true,
    colors: ["#111111", "#E8E8E8", "#C8A96E"],
    colorNames: ["Matte Black", "Cloud White", "Warm Gold"],
    category: "Desk Setup",
    features: [
      "Eye-care flicker-free LED (Ra > 90)",
      "5 brightness levels (100–2000 lux)",
      "3 color temps: Warm / Natural / Daylight",
      "USB-A charging port (5W)",
      "360° flexible arm + 180° head pivot",
      "Touch dimmer with memory",
      "Engineered for 8+ hour sessions",
    ],
    specs: {
      "Light Source": "LED (Ra>90, CRI certified)",
      "Color Temperature": "3000K / 4000K / 6500K",
      Brightness: "5 levels, 100–2000 lux",
      Power: "12W",
      "USB Charging": "5W USB-A",
      Height: "45cm (adjustable)",
      "Eye-Care": "Flicker-free, anti-glare diffuser",
      Warranty: "1 Year",
    },
    inBox: ["MIZAZY DeskLamp Pro", "Power Adapter (1.5m cable)", "User Manual"],
    stock: 38,
  },
];

export const categories = [
  {
    name: "Power",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=700&fit=crop&auto=format",
    count: 12,
  },
  {
    name: "Audio",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=700&fit=crop&auto=format",
    count: 18,
  },
  {
    name: "Mobile Accessories",
    image: "https://images.unsplash.com/photo-1601524909162-ae8725290836?w=600&h=700&fit=crop&auto=format",
    count: 24,
  },
  {
    name: "Smart Gadgets",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=700&fit=crop&auto=format",
    count: 9,
  },
  {
    name: "Desk Setup",
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600&h=700&fit=crop&auto=format",
    count: 15,
  },
  {
    name: "Travel",
    image: "https://images.unsplash.com/photo-1488747279002-2c5b6ca0a7f8?w=600&h=700&fit=crop&auto=format",
    count: 11,
  },
  {
    name: "Lifestyle",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=700&fit=crop&auto=format",
    count: 8,
  },
  {
    name: "New Arrivals",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=700&fit=crop&auto=format",
    count: 6,
  },
];

export const reviews = [
  {
    name: "Arjun Sharma",
    location: "Mumbai",
    rating: 5,
    date: "Aug 2024",
    product: "MIZAZY Buds Pro",
    productId: "buds-pro",
    review:
      "Absolutely blown away by the sound quality. The ANC is on par with products twice the price. MIZAZY has nailed premium without the premium price tag. The case feels incredibly solid.",
    verified: true,
    helpful: 847,
    avatar: "AS",
  },
  {
    name: "Priya Nair",
    location: "Bangalore",
    rating: 5,
    date: "Sep 2024",
    product: "MIZAZY Watch X1",
    productId: "watch-x1",
    review:
      "The AMOLED display is stunning even in direct sunlight. Gets 6 full days easily. The ECG feature was surprisingly accurate — actually caught an irregularity my doctor confirmed.",
    verified: true,
    helpful: 612,
    avatar: "PN",
  },
  {
    name: "Rahul Mehta",
    location: "Delhi",
    rating: 5,
    date: "Oct 2024",
    product: "MIZAZY PowerSlim 20K",
    productId: "powerslim-20k",
    review:
      "The thinnest power bank I have ever owned. Fits in my shirt pocket. Charged my MacBook Air and two iPhones simultaneously on a 6-hour flight. Total game changer.",
    verified: true,
    helpful: 489,
    avatar: "RM",
  },
  {
    name: "Sneha Reddy",
    location: "Hyderabad",
    rating: 4,
    date: "Sep 2024",
    product: "MIZAZY SoundMax Pro",
    productId: "soundmax-pro",
    review:
      "Sound quality is exceptional — LDAC on Spotify HiFi makes a noticeable difference. Ear pads get slightly warm after 3+ hours but the audio is worth it. Packaging is premium too.",
    verified: true,
    helpful: 356,
    avatar: "SR",
  },
  {
    name: "Karthik Rajan",
    location: "Chennai",
    rating: 5,
    date: "Oct 2024",
    product: "MIZAZY GaN 65W",
    productId: "gan-65w",
    review:
      "Replaced three chargers with this one. My MacBook, iPad, and phone all charge simultaneously. The size is almost unbelievable for the output. Daily driver now.",
    verified: true,
    helpful: 723,
    avatar: "KR",
  },
  {
    name: "Anjali Desai",
    location: "Pune",
    rating: 5,
    date: "Nov 2024",
    product: "MIZAZY HubPro 7-in-1",
    productId: "hub-pro-7",
    review:
      "Plug and play — zero driver issues on my M2 MacBook Pro. 4K@60Hz is rock solid, SD card reader is fast. The aluminum build feels premium. Desk looks so much cleaner now.",
    verified: true,
    helpful: 284,
    avatar: "AD",
  },
];

export const bundles = [
  {
    title: "Audio Essentials",
    subtitle: "Buds Pro + NeckPro",
    products: ["buds-pro", "neckpro"],
    discount: 15,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=400&fit=crop&auto=format",
    tag: "Most Popular",
  },
  {
    title: "Power Traveler",
    subtitle: "PowerSlim 20K + GaN 65W",
    products: ["powerslim-20k", "gan-65w"],
    discount: 18,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=400&fit=crop&auto=format",
    tag: "Travel Ready",
  },
  {
    title: "Ultimate Desk Setup",
    subtitle: "HubPro + DeskLamp Pro",
    products: ["hub-pro-7", "desklamp-pro"],
    discount: 20,
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600&h=400&fit=crop&auto=format",
    tag: "Work From Home",
  },
];

export const coupons = [{ code: "MIZAZY10", discountPercent: 10, active: true }];
